name: towards_pandas_1
channels:
  - conda-forge
  - defaults
  - damianavila82
dependencies:
  - python=3.6  # RISE does not work with 3.7 yet
  - pandas=0.23.4
  - matplotlib=2.2
  - jupyter=1.0
  - rise=5.3.0
  - cyberpandas=1.1.1
  - geopandas=0.4.0
  - fletcher=0.1.2
  # scikit-learn dev (0.20) but not in conda
